### ISSUE TITLE
Some gotcha with assembling request Path.

### ISSUE THREAD

**Issue by corvinusy** [emicklei/forest#1]
Hi.
I have found some gotcha with assembling requests like 
    GET: "http://localhost/login?name=aaa&pass=bbb"
The obvious way
    forest.Path("/login").Query("name", "aaa").Query("pass", "bbb") 
results in
   "http://localhost/login/name=aaa&pass=bbb"
which is inappropriate.

I also have found that some lightweight frameworks ("gin-gonic" in my case) use different method names for different ways of parameters extracting, such as 
Param("name") for "/login/:name"
Query("name") for "/login?name"
PostForm("name") for post data 

And my questions: can it be fixed? If yes then can fix be released in mentioned way?
In any case, thank you for your great efforts.
With best regards, corvinusy

**Comment by emicklei** [comment]
@corvinusy , thank you for reporting the issue; there was a failure in the test too :-). 
As for the parameter extraction, I will extend the feature to detect these cases.

**Comment by emicklei** [comment]
@corvinusy , do you want the PostForm function for creating a request or for expectation on the response (or both) ?

**Comment by corvinusy** [comment]
I think PostForm() can be very usable for "application/x-www-form-urlencoded" POST requests.
But I did not check these requests yet.
At this moment idiomatic assembling of GET requests would be more important for me.
Thank you.

**Comment by emicklei** [comment]
I am closing this issue until somebody actually needs the PostForm feature (or if something sends a PR with an implementation :-))
