### ISSUE TITLE
RequestConfig.Content doesn't properly handle JSON string

### ISSUE THREAD

**Issue by mmindenhall** [emicklei/forest#2]
Hello,
The `RequestConfig.Content` method does not detect when the `payload` param is already a JSON string, and therefore does not need to be marshaled.  For example:

```go
var testJson = `{
   "email": "vizzini@example.com",
   "first_name": "Boss",
   "last_name": "Vizzini",
}`
	resp := local.POST(t, Path("/api/v1/platform/:resource_name", "user").Content(testUser1, "application/json"))

// results in string being escaped by json.Marshal, which fails to Unmarshal:
// "{\n   \"email\": \"vizzini@example.com\",\n   \"first_name\": \"Boss\",\n   \"last_name\": \"Vizzini\",\n}"
``` 
See [example in go playground](http://play.golang.org/p/Fvk1gRUgMs).

**Comment by emicklei** [comment]
Thank you for sharing this.

The Content function is indeed a bit confusing here. The current way to pass in a JSON as is, is to set the BodyReader field of the config. This, however, is quite different from the function api.

I propose to change this function (Content) such that is works as expected from your example.  In addition, I will implement an extra validation to verify that the content is correct JSON (or XML if passed "application/xml").

**Comment by emicklei** [comment]
for now, I leave out the validation part until someone requests for it.
