### ISSUE TITLE
Better summary/failure report

### ISSUE THREAD

**Issue by Heanthor** [emicklei/forest#5]
Hi,

I've had problems getting good error reporting from this library. I'm looking for something that lists all the failed tests at the end of the run, as well as basic failure information (failing condition, line number). I've been able to create something like this by implementing my own forest.T, which records line information in the Fail() and FailNow() functions, but the lack of configurability in forest's logging has made getting all the needed information in one place very difficult. 

Are there any plans to make forest work better with this type of report? Just printing out a failure when it happens does not allow a quick glance at what went wrong in a long list of tests and debug printout. I'd appreciate some more APIs to get access to all failed tests, their line numbers, and on which condition they failed. Or is there a better way to do this that already exists?

**Comment by emicklei** [comment]
this package is intented to be used with the standard testing package. That package does not provide the lists you request for. 
So, indeed you could create your own adapator for this. 
Do you have suggestions to make this package more configurable.

**Comment by emicklei** [comment]
The new function  VerboseOnFailure has helped us to get more information when a failure is detected
